### PR TITLE
MongoDB deployment on PIs

### PR DESCRIPTION
**Pull request by nitesh-jaswal**

### CODE REVIEW

**Comment by laszewsk** [comment]
A) improve markdown,

    itemized lists
    empty line after heading

B) codee contains hard coded ips and machine names, make them variable, just as the pi group has done

C) there are files that do not belong in this pull request such as .fuse*

D) no benchmark and example on how to run this is provided

**Comment by nitesh-jaswal** [comment]
> This limitation is unclear. IT must be documented and explained how to change it
> 
> # Currently this value is fixed to a 1 Master and 3 Worker config only. It is recommended to
> # have an odd number of members in replica sets to avoid ties during voting.

Added section "Scope for Improvements" to document this.

**Comment by nitesh-jaswal** [comment]
> Indentations in enumerations are wrong.
> 
> Please review syntax of markdown

Syntax reviewed and corrected

**Comment by nitesh-jaswal** [comment]
Hello Professor
I had intended the Scope for Improvement section to be a guide to someone in case they wanted to update the code in the future, hence the confusion.
I have removed the restriction from the code and allowed the ability to launch replica set in a configuration he wants (provided they follow MongoDB recommendations) via the command itself. I have also removed the hard coded cfg and implemented it using python dicts. The cfg is required to instantiate the replica set and it is now generated and handled in the code itself.

**Pull request closed without merging**
